### ISSUE TITLE
[Bug]: Vite warning due to justify-content: end usage

### ISSUE THREAD

**Issue by marty0678** [ceolter/ag-grid#11888]
### Link to reproducible scenario

Can provide if required, but should be easy to reproduce

### Describe the bug

Steps to reproduce 
1. Create a new Vite project (in my case using Vue but that's probably optional)
2. Install `ag-grid-community@latest ag-grid-enterprise@latest ag-grid-vue3@latest`
3. Add AG Grid to a page
4. Run dev server

Actual behaviour
Warning is logged
```
[vite:css][postcss] end value has mixed support, consider using flex-end instead
5209|    display: flex;
5210|    flex: 1;
5211|    justify-content: end;
   |    ^^^^^^^^^^^^^^^^^^^^^
5212|  }
5213|
[vite:css][postcss] end value has mixed support, consider using flex-end instead
5209|    display: flex;
5210|    flex: 1;
5211|    justify-content: end;
   |    ^^^^^^^^^^^^^^^^^^^^^
5212|  }
5213|
```

Expected behaviour
No warning is logged if justify-content is updated to flex-end / if that works as expected.

More information
Started after I upgraded from 33.3.0 to 34.1.2. Appears to just be cosmetic and haven't noticed any functional issues, but wanted to flag it just in case.

Looks like these two lines would trigger it:

https://github.com/ag-grid/ag-grid/blob/e6528e87d6903694fe2215ba108429ac86b45a8e/documentation/ag-grid-docs/src/components/theme-builder/components/general/GridPreview.tsx#L152

https://github.com/ag-grid/ag-grid/blob/e6528e87d6903694fe2215ba108429ac86b45a8e/community-modules/styles/src/internal/base/parts/_filter-tool-panel.scss#L191

### Version

34.1.2

### Does the issue occur for a specific framework only?

Vue

### Is the issue only observable on a specific browser?

All browsers

**Comment by Chentai-Kao** [comment]
I encountered the same warning after upgrading `ag-grid-community`/`ag-grid-react`/`ag-grid-enterprise` all from `33.0.3` to `34.2.0`.

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil

**Comment by marty0678** [comment]
Hey yeah it's still an issue, it hasn't been solved elsewhere AFAIK. 

I haven't had a chance to create a repro due to time, but yeah it's still an issue. I intend to create a repro when having time just not sure when I'll have a moment. 

Thanks!

**Comment by harveyconnor** [comment]
@AG-Zoheil  This is still an issue.
When starting vite it shows the message
```
vite v5.4.21 building for production...
[vite:css] end value has mixed support, consider using flex-end instead

transforming (12074) node_modules/ag-grid-react/dist/package/index.esm.mjs[vite:css] end value has mixed support, consider using flex-end instead
5703|    display: flex;
5704|    flex: 1;
5705|    justify-content: end;
   |    ^^^^^^^^^^^^^^^^^^^^^
5706|  }
5707|  
```
