### ISSUE TITLE
[Support]: serverSideEnableClientSideSort doesn't return to default order

### ISSUE THREAD

**Issue by howdareme** [ceolter/ag-grid#11903]
### Add a description

When enabling this, i can sort ascending , descending and then null. Null should return it back to the default order it, but it doesn't, it stays in descending state. This seems to be intentional by design, but how do i override this so it on the 3rd sort it goes back to the default column order?

<img width="858" height="546" alt="Image" src="https://github.com/user-attachments/assets/9531c74e-7bfe-4e74-85cd-d39d51ee68cb" />  First pic is the default order, last pic is the 'null' order.

<img width="877" height="542" alt="Image" src="https://github.com/user-attachments/assets/09a26223-3a7d-41c8-a062-cbfc03f0c420" />

### Version

32.3

### What language are you using?

Angular

### What browser are you using?

Chrome

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil

**Comment by avasuro** [comment]
Bug still exists, exists in the backlog and trackable with the following reference and description:
[AG-11521 [SSRM] Allow unsorting rows (reverting to original row order) when using client-side sorting in SSRM](https://www.ag-grid.com/pipeline/?searchQuery=AG-11521)
