### ISSUE TITLE
paginationPageSize property being ignored when setting new DataSource

### ISSUE THREAD

**Issue by denver-HJS** [ceolter/ag-grid#1548]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

My app has its own pagination control section that contains a drop down for changing the page size. When a selection change occurs it triggers a handler that will provide the grid with a new data source with the updated value passed to the `paginationPageSize` property.

However when I do this the page size in the grid remains as what I set it to in the GridOptions definition (as opposed to the DataSource object)

**Expected behavior**

The number of rows displayed per page should change to the value assigned to the DataSource object's `paginationPageSize`

See: #209 

**Minimal reproduction of the problem with instructions**
This is the relevant piece of the handler that fires to set the new data source:

```
 self.options.api.setDatasource({
                        paginationPageSize: parseInt(self.selectedPageSize, 10),
                        rowCount: data.length,
                        getRows: (params) => supplyGridRows(data, params)
                    });
```
Attached screenshot shows the page size being set to 5, but the grid still displaying the 10 rows. I can provide the rest of the code that links everything if needed, but I left it out for brevity.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
I'm running Windows 7. The code base is using ES6 syntax running in the latest Chrome.

* **ag-Grid version:** 8.2.0

* **Browser:** Chrome 57.0.2987.110

* **Language:** ES6

![image](https://cloud.githubusercontent.com/assets/1916018/24273998/d4ff5a28-0fe2-11e7-9abc-318bc036e939.png)

**Comment by seanlandsman** [comment]
Hi

Issue  AG-356 raised our side for this - we'll update this thread as soon as we have further information.

thanks

**Comment by denver-HJS** [comment]
Hi,

I appreciate the reply. My project has a deadline to make at the end of this month, and I'm wondering if there's any update on this?

Thanks!

**Comment by seanlandsman** [comment]
Hi @denver-HJS - sorry for not replying yesterday, I was off ill

We released 9.0.0 yesterday - can you please try that and see if it resolves your problem?

**Comment by denver-HJS** [comment]
@seanlandsman, no worries. Unfortunately the problem is still there after updating to version 9.0.0

I'll attach some screenshots to illustrate.

![image](https://cloud.githubusercontent.com/assets/1916018/24513975/8cf92f02-1527-11e7-9b4d-fa6380adc403.png)
![page_drop_down](https://cloud.githubusercontent.com/assets/1916018/24513993/9da6f168-1527-11e7-97ca-52bdf08ad0e4.png)
![page_size_breakpoint](https://cloud.githubusercontent.com/assets/1916018/24514001/a3ac7376-1527-11e7-8a58-f1e8a258f8c6.png)
![page-size_count](https://cloud.githubusercontent.com/assets/1916018/24514008/ab200ed8-1527-11e7-8514-87b13547a6a5.png)

**Comment by denver-HJS** [comment]
Hi,

I've got an update - after upgrading to version 9.1.0 I'm able to use the API function `paginationSetPageSize` function successfully i.e. `self.internalDataGridOptions.api.paginationGoToPage(self.viewModel.currentPage);`

Whatever changes were done must've fixed this issue, so many thanks!
