### ISSUE TITLE
Floating filter field does not accept typing decimal marks

### ISSUE THREAD

**Issue by clamonsch** [ceolter/ag-grid#1586]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Typing a decimal number (e.g. 4.7) into floating filters on columns is not possible although filtering with decimal numbers is generally possible. Entering a decimal number in the main column filter as well as pasting a decimal number into the floating filter is possible. Entering a decimal number via typing on the other hand is not possible. 

**Expected behavior**
Being able to type a number with decimal mark (e.g. 4.7) into the floating filter.

**Minimal reproduction of the problem with instructions**

- Brows to grid demo https://www.ag-grid.com/example.php
- Enter the floating filter of column "Total Winnings"
- Try to enter the following number: 55.5 => this is not possible
- Copy a decimal value from any cell of this column
- Enter again the floating filter of column "Total Winnings"
- Paste (ctrl + v) the value => works fine

See screenshots:

![pasting-decimal-value-ok](https://cloud.githubusercontent.com/assets/11771812/24915371/3ebd5b74-1ed7-11e7-87a3-bca938b2bbfb.png)
![typing-decimal-mark-not-possible](https://cloud.githubusercontent.com/assets/11771812/24915372/3ec15e54-1ed7-11e7-8ae2-e245fed0cb6c.png)

**What is the motivation / use case for changing the behavior?**
It's a bug.

**Please tell us about your environment:**
Official AG grid demo: https://www.ag-grid.com/example.php
Reproduced with Chrome, Vivaldi and Firefox.

* **ag-Grid version:** X.X.X
latest (2017-04-11)

* **Browser:**
Chrome, Vivaldi and Firefox

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

We are going to look into this as part of this ticket: AG-392, this should be fixed on the next release, we will close this ticket as soon as the release is out.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Just to le you know that as of 10.1.0 this is available.

Please check the changelog

Thanks

**Comment by zihniogmen** [comment]
Hello,

This bug is still continues at my end. I'm not able to type neither dot or comma but I'm able to copy into filter input box from somewhere else.

Ag-Grid Version 
ag-Grid v12.0.0

Browser:
Chrome 59.0.3071.115 x64

Language :
Pure JS



Plunker Address :
https://plnkr.co/edit/UtxzoQuneFFSaYOr0iPN?p=preview

**Comment by ranjithfullstackdeveloper** [comment]
Is this issue is fixed?
