### ISSUE TITLE
Data Export for Grouping Headers

### ISSUE THREAD

**Issue by ataft** [ceolter/ag-grid#482]
The grouping headers do not appear in a data export, even with "skipHeader: false".  Since delimited files have no concept of column span, the expected behavior would be to repeat the Header Group for each column.  The use case for this is when column titles are the same and only differentiated by the header group, such as a standard pivot table.

**Comment by ceolter** [comment]
in summary, the grouped columns should include the group name in their header. right?

**Comment by ataft** [comment]
The "headerGroup" title from the columnDef should be shown.  I was thinking it would be best as a separate row than the "headerName", but perhaps a concatenation of "headerGroup - headerName" is  better.  Either way works for me.

**Comment by ceolter** [comment]
the second way is better suited to tools that read in csv, having the first row (only) showing headers is pretty standard.

**Comment by ataft** [comment]
good call

**Comment by yarshad** [comment]
Hi,
Is this feature available now? or is there a workaround available to export the group headers?

Thanks

**Comment by ceolter** [comment]
nope, haven't come back to this since.

**Comment by hanning2014** [comment]
hi, Data Export for Grouping Headers is ok, now ?

**Comment by ceolter** [comment]
implementing this now, along with export to XLS. will be in next release.

**Comment by ceolter** [comment]
done. export to xls done. csv and xls export now allow exporting column headers.

**Comment by SERGEES** [comment]
@ceolter hi what if I need to export to excel grid with spanned rows or columns
https://www.ag-grid.com/javascript-grid-row-spanning/
It looks like the grid doesn't support it... am I right or I miss something?

**Comment by mravenash** [comment]
Is there a plunker/sandbox for this? I am still having this issue. The group headers are not shown in excel on export. Any input is appreciated.
Regards
Avenash
