### ISSUE TITLE
Is there is any way to hide filter icon? I need filter functionalities only  using api. 

### ISSUE THREAD

**Issue by sasikumar25** [ceolter/ag-grid#788]
For past 1  month i'm using ag-grid. i'm facing a pbm that i have to hide the filter icon while mouse over to column header but i need the filter functionalities through filter api.

**Comment by fkoulba** [comment]
Try using "suppressMenu: true" in column definition.

**Comment by sasikumar25** [comment]
Thanks fkoulba this is solved my pbm.
 ag-grid has more functionalities but is not properly documented.

**Comment by randdusing** [comment]
This isn't working for me. Even with ``` suppressMenu: true```, I can still see the filter icon.

**Comment by ceolter** [comment]
suppressMenu - stops the menu from appearing.

this does not stop the filter icons from appearing.

if you want no filter icon, then don't filter by that column!!!

or - change the header template, and provide a template that is missing the filter icon.

**Comment by dharric** [comment]
Ceolter. What about when a user resets the filter so that all filtering is removed? The filter icon should go away then.

**Comment by ceolter** [comment]
```user resets the filter so that all filtering``` => it is removed when no filter active.

**Comment by ClayShentrup** [comment]
floatingFilterComponentParams: {
      suppressFilterButton: true,
    },
