### ISSUE TITLE
selectAllOnCurrentPage selects all records

### ISSUE THREAD

**Issue by hanczkamartanatalia** [ceolter/ag-grid#9709]
Hi,
I have a problem with checkboxes.
When I select the headerCheckbox on the last page, all rows are selected. The problem only occurs on the last page. On the rest it works fine. The problem only occurs when footers are used

expectations: only the last page is selected
current: all pages are selected

**Comment by AG-Zoheil** [comment]
Hi @hanczkamartanatalia,

Please see this addressed in our documentation here: https://www.ag-grid.com/javascript-data-grid/row-selection-multi-row/#selecting-all-rows.

Kind regards,
Zoheil

**Comment by hanczkamartanatalia** [comment]
Hi @AG-Zoheil 

I have the "currentPage" option selected but it doesn't solve my problem. The attached documentation does not mention anything about different behavior for the last page. Also the table attached there does not behave like this on the last page.

Rgrds

**Comment by AG-Zoheil** [comment]
Hi @hanczkamartanatalia,

Thanks for the reply.

The link to the documentation shows that this behaviour works as expected when configured currently - i.e. `currentPage`. There is no different behaviour for the last page. You can navigate to the last page and select all in the example and it works the way it is intended to. 

We do not provide support on Github but only take bug reports, and as this is working and not a bug we'd be unable to help further outside of our enterprise licence.

Kind regards,
Zoheil
